# Python CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-python/ for more details
version: 2

aliases:
  - &defaults
    docker:
      - image: cimg/node:current-browsers
    working_directory: ~/projects/reel2bits.org

  - &attach_workspace
      attach_workspace:
        at: ~/projects/

  - &build_and_sync_site
      steps:
        - checkout
        - *attach_workspace
        - add_ssh_keys:
            fingerprints:
              - "99:b1:9e:a7:63:31:54:d9:4d:29:f3:9a:44:75:35:c9"
        - run:
            name: Install rsync
            command: |
              sudo apt-get update
              sudo apt-get install -y rsync
        - run:
            name: Install dependencies
            command: |
              yarn
        - run:
            name: Build website
            command: |
              yarn i18n-compile
              yarn build
              cp -r src/assets dist/
        - deploy:
            name: deploy
            command: |
              rsync -avc -e "ssh -o StrictHostKeyChecking=no -p 22" --delete dist/ reel2bits.org@cadance.licorn.eu:/

  - &build
      steps:
        - checkout
        - *attach_workspace
        - add_ssh_keys:
            fingerprints:
              - "99:b1:9e:a7:63:31:54:d9:4d:29:f3:9a:44:75:35:c9"
        - run:
            name: Install dependencies
            command: |
              yarn
        - run:
            name: Build website
            command: |
              yarn i18n-compile
              yarn build

jobs:
  build-website:
    <<: *defaults
    docker:
      - image: cimg/node:current-browsers
    <<: *build_and_sync_site
  test-build:
    <<: *defaults
    docker:
      - image: cimg/node:current-browsers
    <<: *build

workflows:
  version: 2
  build-website:
    jobs:
      - test-build
      - build-website:
          requires:
            - test-build
          filters:
            branches:
              only: master
